### ISSUE TITLE
Large Scale Sparse Linear Programs

### ISSUE THREAD

**Issue by schmidt73** [oxfordcontrol/Clarabel.rs#123]
I am attempting to use Clarabel to solve a large scale, sparse linear program, as accessed through the CVXPY interface to Clarabel. However, I'm having some trouble, in that it appears the linear system solving step takes prohibitively long. For example, the following instance with about 5 million constraints and 400 thousand variables hangs for over 30 minutes with the following output.

```
-------------------------------------------------------------
           Clarabel.rs v0.7.1  -  Clever Acronym

                   (c) Paul Goulart                                                                                                                                                                           University of Oxford, 2022
-------------------------------------------------------------

problem:
  variables     = 412686
  constraints   = 4749546
  nnz(P)        = 0
  nnz(A)        = 12581604
  cones (total) = 2
    :        Zero = 1,  numel = 8145
    : Nonnegative = 1,  numel = 4741401

settings:
  linear algebra: direct / qdldl, precision: 64 bit
  max iter = 200, time limit = Inf,  max step = 0.990
  tol_feas = 1.0e-8, tol_gap_abs = 1.0e-8, tol_gap_rel = 1.0e-8,
  static reg : on, ϵ1 = 1.0e-8, ϵ2 = 4.9e-32
  dynamic reg: on, ϵ = 1.0e-13, δ = 2.0e-7
  iter refine: on, reltol = 1.0e-13, abstol = 1.0e-12,
               max iter = 10, stop ratio = 5.0
  equilibrate: on, min_scale = 1.0e-5, max_scale = 1.0e5
               max iter = 10

iter    pcost        dcost       gap       pres      dres      k/t        μ       step
---------------------------------------------------------------------------------------------
```

In attempting to understand this, I have the following three questions:

- Is Clarabel appropriate for large scale, sparse linear programming problems?
- Could this be an issue with the linear system solver QDLDL?
- On your benchmarks in the manuscript, Clarabel outperforms HiGHS, however, my tests show that Clarabel is massively outperformed by HiGHS for the large-scale, sparse linear programs I am studying. Do you have any thoughts on this?

Thank you for your assistance.

**Comment by schmidt73** [comment]
Thank you both for the quick response. You were right that the main bottleneck is the built-in `QDLDL` solver. Swapping this out with `faer` led to a large performance gain. However, it still appears HiGHS is quite a bit faster for this class of sparse linear programs, as described below.

To provide a (crude) benchmark for the performance I am seeing, I compared Clarabel.rs version `0.9.0` using the `faer` linear system solver to HiGHS `1.2.0` with default settings. On the attached instance containing 412,686 variables and 4,749,546 constraints, HiGHS terminated in `39.54` seconds, with the following log:

```
Running HiGHS 1.2.0 [date: 2021-07-09, git hash: n/a]
Copyright (c) 2022 ERGO-Code under MIT licence terms
Presolving model
3916029 rows, 404541 cols, 11559563 nonzeros
3820114 rows, 404541 cols, 11384211 nonzeros
Presolve : Reductions: rows 3820114(-929432); columns 404541(-8145); elements 11384211(-1197393)
Solving the presolved LP
Using EKK dual simplex solver - serial
  Iteration        Objective     Infeasibilities num(sum)
          0     0.0000000000e+00 Ph1: 0(0) 27s
       5505    -8.3668942317e+03 Pr: 0(0) 32s
       5505    -8.3668942317e+03 Pr: 0(0) 32s
Solving the original LP from the solution after postsolve
Model   status      : Optimal
Simplex   iterations: 5505
Objective value     : -8.3668942317e+03
HiGHS run time      :         39.54
Solver terminated with message: Optimization terminated successfully. (HiGHS Status 7: Optimal)
```

In contrast, Clarabel took around an `2301.85` seconds to terminate, with the following log. 

```
-------------------------------------------------------------
           Clarabel.rs v0.9.0  -  Clever Acronym

                   (c) Paul Goulart
                University of Oxford, 2022
-------------------------------------------------------------

problem:
  variables     = 412686
  constraints   = 4749546
  nnz(P)        = 0
  nnz(A)        = 12581604
  cones (total) = 2
    :        Zero = 1,  numel = 8145
    : Nonnegative = 1,  numel = 4741401

settings:
  linear algebra: direct / faer, precision: 64 bit
  max iter = 200, time limit = Inf,  max step = 0.990
  tol_feas = 1.0e-8, tol_gap_abs = 1.0e-8, tol_gap_rel = 1.0e-8,
  static reg : on, ϵ1 = 1.0e-8, ϵ2 = 4.9e-32
  dynamic reg: on, ϵ = 1.0e-13, δ = 2.0e-7
  iter refine: on, reltol = 1.0e-13, abstol = 1.0e-12,
               max iter = 10, stop ratio = 5.0
  equilibrate: on, min_scale = 1.0e-4, max_scale = 1.0e4
               max iter = 10

iter    pcost        dcost       gap       pres      dres      k/t        μ       step
---------------------------------------------------------------------------------------------
  0  -9.3631e+03  -9.2087e+06  9.83e+02  8.96e-01  3.61e+01  1.00e+00  4.44e+00   ------
  1  -6.4705e+03  -3.8401e+06  5.92e+02  6.29e-01  3.28e+01  1.46e+00  3.24e+00  5.08e-01
  2  -6.0388e+03  -3.3031e+06  5.46e+02  5.75e-01  3.23e+01  2.28e+00  2.98e+00  2.41e-01
  3  -5.5142e+03  -2.1339e+06  3.86e+02  4.46e-01  2.98e+01  2.94e+00  2.36e+00  3.92e-01
  4  -5.2210e+03  -1.3278e+06  2.53e+02  3.24e-01  2.61e+01  2.61e+00  1.76e+00  4.34e-01
  5  -5.0978e+03  -7.7326e+05  1.51e+02  2.15e-01  2.08e+01  1.70e+00  1.20e+00  4.95e-01
  6  -5.1442e+03  -3.8860e+05  7.45e+01  1.21e-01  1.33e+01  7.84e-01  6.92e-01  6.09e-01
  7  -5.1535e+03  -3.2953e+05  6.29e+01  1.04e-01  1.14e+01  5.42e-01  5.98e-01  3.74e-01
  8  -5.1717e+03  -2.8313e+05  5.37e+01  9.07e-02  9.41e+00  2.65e-01  5.21e-01  6.75e-01
  9  -5.4556e+03  -1.4078e+05  2.48e+01  4.79e-02  4.98e+00  1.13e-01  2.81e-01  5.55e-01
 10  -5.7473e+03  -1.0012e+05  1.64e+01  3.51e-02  3.67e+00  5.87e-02  2.09e-01  4.91e-01
 11  -6.1032e+03  -6.6149e+04  9.84e+00  2.36e-02  2.44e+00  3.29e-02  1.43e-01  3.99e-01
 12  -6.1621e+03  -6.4172e+04  9.41e+00  2.30e-02  2.39e+00  2.90e-02  1.40e-01  1.43e-01
 13  -6.4130e+03  -5.1854e+04  7.09e+00  1.86e-02  1.95e+00  1.94e-02  1.15e-01  3.35e-01
 14  -6.5604e+03  -4.6302e+04  6.06e+00  1.66e-02  1.76e+00  1.42e-02  1.04e-01  3.21e-01
 15  -6.8366e+03  -3.5999e+04  4.27e+00  1.26e-02  1.35e+00  8.62e-03  8.06e-02  4.16e-01
 16  -6.8994e+03  -3.4144e+04  3.95e+00  1.19e-02  1.28e+00  7.18e-03  7.63e-02  2.35e-01
 17  -7.1006e+03  -2.8452e+04  3.01e+00  9.49e-03  1.05e+00  5.10e-03  6.25e-02  3.03e-01
 18  -7.1251e+03  -2.7713e+04  2.89e+00  9.18e-03  1.02e+00  4.59e-03  6.07e-02  1.58e-01
 19  -7.1828e+03  -2.6194e+04  2.65e+00  8.52e-03  9.52e-01  3.81e-03  5.68e-02  2.62e-01
 20  -7.4051e+03  -2.1316e+04  1.88e+00  6.33e-03  7.29e-01  2.57e-03  4.38e-02  3.31e-01
 21  -7.4051e+03  -2.1287e+04  1.87e+00  6.32e-03  7.28e-01  2.55e-03  4.37e-02  1.96e-02
 22  -7.4434e+03  -2.0478e+04  1.75e+00  5.95e-03  6.90e-01  2.30e-03  4.14e-02  1.32e-01
 23  -7.5009e+03  -1.9235e+04  1.56e+00  5.37e-03  6.31e-01  1.90e-03  3.79e-02  2.59e-01
 24  -7.6052e+03  -1.7355e+04  1.28e+00  4.48e-03  5.38e-01  1.46e-03  3.23e-02  3.04e-01
 25  -7.7416e+03  -1.5211e+04  9.65e-01  3.44e-03  4.26e-01  1.04e-03  2.57e-02  3.39e-01
 26  -7.7408e+03  -1.5201e+04  9.64e-01  3.43e-03  4.26e-01  1.03e-03  2.56e-02  1.56e-02
 27  -7.7543e+03  -1.4931e+04  9.26e-01  3.30e-03  4.11e-01  9.65e-04  2.47e-02  1.08e-01
 28  -7.7567e+03  -1.4574e+04  8.79e-01  3.14e-03  3.92e-01  8.29e-04  2.35e-02  3.14e-01
 29  -7.8464e+03  -1.3446e+04  7.14e-01  2.57e-03  3.30e-01  6.55e-04  1.98e-02  2.55e-01
 30  -7.8583e+03  -1.3191e+04  6.79e-01  2.45e-03  3.15e-01  5.98e-04  1.89e-02  1.78e-01
 31  -7.9239e+03  -1.2347e+04  5.58e-01  2.02e-03  2.66e-01  4.63e-04  1.60e-02  3.46e-01
 32  -8.0708e+03  -1.0675e+04  3.23e-01  1.18e-03  1.63e-01  2.31e-04  9.85e-03  7.32e-01
 33  -8.0749e+03  -1.0536e+04  3.05e-01  1.11e-03  1.54e-01  2.07e-04  9.32e-03  2.88e-01
 34  -8.1103e+03  -1.0223e+04  2.61e-01  9.50e-04  1.34e-01  1.73e-04  8.09e-03  2.53e-01
 35  -8.1246e+03  -1.0075e+04  2.40e-01  8.75e-04  1.24e-01  1.56e-04  7.51e-03  2.05e-01
 36  -8.1612e+03  -9.7671e+03  1.97e-01  7.16e-04  1.03e-01  1.24e-04  6.25e-03  3.27e-01
 37  -8.2032e+03  -9.4231e+03  1.49e-01  5.40e-04  7.93e-02  9.00e-05  4.82e-03  4.63e-01
 38  -8.2138e+03  -9.3369e+03  1.37e-01  4.96e-04  7.32e-02  8.16e-05  4.45e-03  1.77e-01
 39  -8.2326e+03  -9.2092e+03  1.19e-01  4.29e-04  6.40e-02  7.04e-05  3.89e-03  1.77e-01
 40  -8.2535e+03  -9.0004e+03  9.05e-02  3.27e-04  4.91e-02  4.85e-05  3.00e-03  7.91e-01
 41  -8.3108e+03  -8.6768e+03  4.40e-02  1.57e-04  2.44e-02  2.36e-05  1.50e-03  5.44e-01
 42  -8.3318e+03  -8.5506e+03  2.63e-02  9.35e-05  1.46e-02  1.35e-05  9.03e-04  6.63e-01
 43  -8.3383e+03  -8.5129e+03  2.09e-02  7.43e-05  1.17e-02  1.06e-05  7.22e-04  4.03e-01
 44  -8.3475e+03  -8.4647e+03  1.40e-02  4.97e-05  7.85e-03  7.04e-06  4.86e-04  4.30e-01
 45  -8.3487e+03  -8.4555e+03  1.28e-02  4.53e-05  7.15e-03  6.24e-06  4.43e-04  5.41e-01
 46  -8.3643e+03  -8.3792e+03  1.77e-03  6.25e-06  9.96e-04  8.59e-07  6.19e-05  8.97e-01
 47  -8.3660e+03  -8.3713e+03  6.45e-04  2.27e-06  3.63e-04  3.09e-07  2.25e-05  7.50e-01
 48  -8.3667e+03  -8.3678e+03  1.24e-04  4.37e-07  7.00e-05  5.96e-08  4.34e-06  8.16e-01
 49  -8.3669e+03  -8.3669e+03  4.42e-06  1.55e-08  2.49e-06  2.10e-09  1.54e-07  9.74e-01
 50  -8.3669e+03  -8.3669e+03  4.44e-08  1.56e-10  2.50e-08  2.11e-11  1.55e-09  9.90e-01
 51  -8.3669e+03  -8.3669e+03  2.24e-09  7.85e-12  1.26e-09  1.04e-12  7.66e-11  9.50e-01
---------------------------------------------------------------------------------------------
Terminated with status = Solved
solve time = 2301.859647154s
```

Looking at the number of simplex iterations HiGHS used, however, the performance of HiGHS is suspicious, since one would expect many more than `5505` simplex iterations to solve a linear program of this magnitude. The linear program I am solving is _essentially_ a relaxation of the integer programming formulation described in [https://link.springer.com/article/10.1007/s11590-014-0754-6](https://link.springer.com/article/10.1007/s11590-014-0754-6), which is obviously very sparse. Perhaps there is a special structure to this linear program which the simplex solver is able to pick up on? The small number of simplex pivots is quite surprising to me.

While the impressive performance of the simplex solver for this class of linear programs remains a mystery to me, I very much appreciate your assistance and feedback. Clarabel (and related software) is a fantastic tool for conic programming problems, and is made more valuable by the active community surrounding the tool.

**Comment by mipals** [comment]
I do not have much experience with the simplex method, so I can not give a concrete answer as to why it is much better for this particular problem. It might simply be that it is a problem that is easy for the simplex method.

However, I did notice that the presolve step of HiGHS removes quite a bit of rows. Roughly speaking this means that HiGHS and Clarabel are not solving the same problem but rather equivalent problems. It could be that HiGHS removes some troublesome rows/columns/constraints. My experience (albeit for the presolve in MOSEK), is that the presolve step can have quite a big impact on the number of iterations. Try to disable the presolve of HiGHS and compare again.

Also, while `faer` is an upgrade to the standard `qdldl`, there are more optimized sparse linear solvers out there. My experience is that using PanuaPardiso is +2x faster than `faer`.

Lastly, it does not surprise me that HiGHS is faster for LPs. It is tailor-made for LPs whereas Clarabel is a more general solver. It is only natural that a more general solver is slower, albeit not so much slower as is the case of your example.

**Comment by goulart-paul** [comment]
The presolve can definitely help a lot in many cases, although it looks like it only removed about a quarter of the constraints here.   Hard to say whether that was the difference maker, although you can probably disable it in HiGHS if you want to make a more direct comparison.

Overall though, your results look like just *one* interior point iteration is taking about 45 seconds.   Even with a massive improvement in the linear solve step speed (using Pardiso or similar), that's not going to close the gap with HiGHS on this example.    It could be that the problem is particularly well suited to the simplex method, or that some other interior point strategy (e.g. a further condensation of the linear system to positive definite form) would have be better.    Have you tried another interior point method for comparison, e.g. Mosek?  I think (but am not certain) that Gurobi would also use simplex if it as an LP.

**Comment by schmidt73** [comment]
I have compared Clarabel to other interior point solvers and the behavior is quite similar, though I have not tested other simplex solvers. I am tempted to agree with Mikkel -- perhaps this problem is particularly well suited for the simplex algorithm. At any rate, it is not a problem with Clarabel.

Thank you both for the suggestions and assistance.
