### ISSUE TITLE
InsufficientProgress status

### ISSUE THREAD

**Issue by maarten837** [oxfordcontrol/Clarabel.rs#126]
I raised the [following issue](https://github.com/cvxpy/cvxpy/issues/2506) with CVXPY two weeks ago, but since it's related to both CVXPY and Clarabel, I would also like to raise it here.

For infeasible problems, I noticed that Clarabel sometimes returns an InsufficientProgress status. What is the interpretation of this? 

I checked the [docs](https://docs.juliahub.com/Clarabel/g676L/0.4.0/autodocs/), but this didn't help me much. I'm asking because the InsufficientProgress is mapped to a SolverError in CVXPY, which is creating some issues in my workflow where I catch infeasible solutions. Would it be appropriate to map this to a different status in CVXPY? 

Thanks a lot!

**Comment by PTNobel** [comment]
I think this is the same as #120?

**Comment by maarten837** [comment]
Thanks for pointing this out. You're right it's the same, I scanned the board before posting but didn't connect the two. 

I'll close this issue then.
