### ISSUE TITLE
Clarabel 0.4.1 v.s. 0.5.0 - Is a (relatively) high difference in dual variables expected?

### ISSUE THREAD

**Issue by lequant40** [oxfordcontrol/Clarabel.rs#31]
Hello there,

I am trying to migrate to version 0.5.0 of Clarabel in Python.

On my test set of problems, I noticed neglictible differences in primal variables (let's say, about the order of the default eps 1e-8), but I also noticed non-neglictible differences in dual variables of ~5e-3.

Attached a reproducer, with output.

=> My question would be: are these differences expected?

Cheers,

Roman
[clarabel.txt](https://github.com/oxfordcontrol/Clarabel.rs/files/11335574/clarabel.txt)

**Comment by lequant40** [comment]
One remark, with another solver (commercial), I find that the first dual variable is equal to -0.02059855 (v.s. -0.01663 for 0.5.0, v.s. -0.02158 for 0.4.1), so I guess there might be a "degradation" with v0.5.0 in this regard.

**Comment by goulart-paul** [comment]
Are you certain that the dual optimizer is unique in that problem?   It appears that the part of A that forms the SOC constraint is rank deficient, so it might be that you can vary the multipliers within the kernel of that matrix.   That's just a guess though.

What does ECOS give you?

**Comment by lequant40** [comment]
Ah yes, I confirm the initial problem has not a unique (primal) solution, so, this can explain.

Re. ECOS, I am not interfaced directly with it, so, it will take a little time to answer, please bear with me :-) !

**Comment by goulart-paul** [comment]
You might find CVXPY useful for testing stuff like this.   Using your data above, you can do something like this (untested):

```python
import cvxpy as cp

# Define and solve the CVXPY problem.
x = cp.Variable(4)
eq_constraints = [
      A[0:1,:] @ x - b[0] == 0
]
nn_constraints = [
      A[1:9,:] @ x - b[1:9] <= 0
]
v = A[9:,:] @ x  - b[9:]
soc_constraints = [
      cp.SOC(-v[0],v[1:])
]
constraints = eq_constraints + nn_constraints + soc_constraints

prob = cp.Problem(cp.Minimize(q.T@x),
                  constraints)

# take your pick here...
prob.solve(solver="CLARABEL",verbose=True)
# prob.solve(solver="ECOS",verbose=True)
# prob.solve(solver="SCS",verbose=True)
```

**Comment by lequant40** [comment]
I confirm everything is in order, thanks for the pointer to CVXPY.
