### ISSUE TITLE
return cost_dual in the solution

### ISSUE THREAD

**Issue by wjzhou-ep** [oxfordcontrol/Clarabel.rs#67]
Thank you for the project. It is both fast and stable for our usage.

Could we add the cost_dual in the solution? (and the Python API )
https://github.com/oxfordcontrol/Clarabel.rs/blob/b6f7bf9be089ee479191570f7acdc01bff9dcdda/src/solver/implementations/default/solution.rs#L61
https://github.com/oxfordcontrol/Clarabel.rs/blob/b6f7bf9be089ee479191570f7acdc01bff9dcdda/src/python/impl_default_py.rs#L68

Use case:
Sometimes, we got AlmostSolved. Currently, we print a warning message for ourselves and recheck manually later.

However, from the the value returned in solution, we don't know the tol_gap, so we would need to regenerate the whole data and re-run the solver with verbose=True to get the that information.

Ideally, we would like to investigate cases that has wider gap, e.g. we would like to check cases with 5e-5 gap instead of 1.1e-8 case. But currently, we would have to run the solver again first to know that.

Another benefit is that, we probably can downgrade the 1e-7 case from warning to info. (We still want to keep the 1e-8 for tol_gap so the solver tries harder instead of declare optimal at 1e-7)

**Comment by wjzhou** [comment]
Thank you for fixing this so quickly.
