### ISSUE TITLE
What about https://github.com/oxfordcontrol/Clarabel.rs/blob/main/src/python/.github/workflows/CI.yml

### ISSUE THREAD

**Issue by tschm** [oxfordcontrol/Clarabel.rs#98]
I don't understand the exact purpose of this file. When would it be triggered?
I should also be taken care of by the dependabot as some of the GitHub actions are rather dated by now

**Comment by goulart-paul** [comment]
I agree and have removed it.   I don't remember what it was for -- possibly the python interface was originally planned as its own repository and later moved here.
